# Récupérer toutes les catégories
GET http://localhost:3000/categories

# Récupérer une catégorie avec un ID spécifique
###
GET http://localhost:3000/categories/1

# Créer une nouvelle catégorie
###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "nom": "Santé"
}

# Mettre à jour une catégorie existante
###
PATCH http://localhost:3000/categories/5
Content-Type: application/json

{
  "nom": "Voyage"
}

# Supprimer une catégorie existante
###
DELETE http://localhost:3000/categories/1
