# Récupérer tous les commentaires
GET http://localhost:3000/commentaires

# Récupérer un commentaire avec un ID spécifique
###
GET http://localhost:3000/commentaires/1

# Créer un nouveau commentaire
###
POST http://localhost:3000/commentaires
Content-Type: application/json

{ 
  "email": "elbachahasna1@gmail.com",
  "contenu": "Extra-ordinaire",
  "articleId": 1
}

# Mettre à jour un commentaire existant
###
PATCH http://localhost:3000/commentaires/2
Content-Type: application/json

{
  "contenu": "Oooh! extra-ordinaire"
}

# Supprimer un commentaire existant
###
DELETE http://localhost:3000/commentaires/1
